sonar.projectKey=Splitora_splitora-server
sonar.organization=splitora-1
sonar.host.url=https://sonarcloud.io

# Java settings
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java

# Test coverage (if using Jacoco)
sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
