spring:
    # Connection of spring application with database
    application:
        name: splitora

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        open-in-view: false

    logging:
        config: classpath:logback-spring.xml
        file:
            name: /var/logs/app.log

    mail:
        enabled: false
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID:abc123}
                        client-secret: ${GOOGLE_CLIENT_SECRET:good123}
                        scope:
                            - openid
                            - email
                            - profile
                        redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:3000/callback}
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: name

server:
    port: 8081

allowed:
    origins: ${ALLOWED_ORIGINS:http://localhost:3000}

# JWT security
jwt:
    access:
        secretKey: ${JWT_ACCESS_SECRET:SuP9ErKeY}
        expirationTimeInMinutes: ${JWT_ACCESS_EXPIRATION:150}
    refresh:
        secretKey: ${JWT_REFRESH_SECRET:wUP89ErKie}
        expirationTimeInMinutes: ${JWT_REFRESH_EXPIRATION:2000}

# monitoring
management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus, metrics
    endpoint:
        health:
            show-details: always
        prometheus:
            enabled: true
        tags:
            application: splitora

# File path for the report
my:
    reportFilePath: ${REPORT_FILE_PATH:/path}